- .github/workflows/build-ot3.yml
- buildspec.yml
- start.sh
To avoid having to set up aws webhooks, we can try triggering the codebuild with [this aws-maintained action](https://github.com/aws-actions/aws-codebuild-run-build) and posting the result in slack.
> chore(build): add gh actions trigger to codebuild

- .gitmodules
We used to have main of this repo pulling opentrons-recipe of the
opentrons metalayer, but now that's merged it can (and needs to be) main.
> chore: meta-opentrons: branch main

- .github/workflows/build-ot3.yml
- .gitmodules
The build id output from the codebuild action encoded the build project into the name, which we don't want, so remove it with a bashism. Also fix some other stuff about the url and make it (slightly) more readable.
> fix(build): Correct cf output url

- Dockerfile
- README.md
- ot3Image.sh
- start.sh
You can now specify arguments to `ot3Update.sh` and have them forwarded
to bitbake. In addition, we now under the hood build the docker image
with a tempdir context that's empty except for `start.sh`, so it's a lot faster.
> chore(build): slight build speedups, more capability

- buildspec.yml
- start.sh
This should speed things up some hopefully. We can get more aggressive
by actually caching build results, but doing the state and the downloads
should help.
> chore(build): reenable caching on codebuild

- Dockerfile
- buildspec.yml
The old letsencrypt root CA expired in favor of a new one; the OS needs
updates to handle this since git.yoctoproject.org uses letsencrypt certs.
> chore: update dockerfile to get new CA store

- buildspec.yml
The thing we were missing  with previous caching effort was saving the [sstate cache](https://wiki.yoctoproject.org/wiki/Enable_sstate_cache) along with the downloads folder. By caching both sstate and downloads, we bring the builds down to about an hour. We can also save buildstats for later perusal and put them in the artifact store.
> core: re-add download caching

- buildspec.yml
The AWS EC2 vms that back codebuild still have ubuntu glibc with [bug 1962606](https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1962606) which means that if you blindly upgrade everything (which `apt-get upgrade` does, even if you give it a specific package name) then `apt-get` will fail because the kernel minor version is too high. If you instead use `apt-get install --only-upgrade <packagename>` then it will only try to upgrade that package, and not the kernel, and the problem is avoided... for now anyway. Probably the better path in the future is a different method to make sure ca-certificates is up to date or a more docker-native setup.
> buildspec: only upgrade ca-certificates not kernel

- build/conf/local.conf
[RET-1205](https://opentrons.atlassian.net/browse/RET-1205)
CI build [oe-core-run:8039613853](https://github.com/Opentrons/oe-core/runs/8039613853) is failing because we run out of diskspace. So add rm_recipe to the local.conf file which will remove recipe source files after the recipe is built.
> RET-1205 Remove recipe source files are they are built to save diskspace

- layers/meta-opentrons/conf/machine/verdin-imx8mm.conf
- layers/meta-opentrons/recipes-graphics/wayland/files/imx/weston.ini
- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
- layers/meta-opentrons/recipes-kernel/linux/device-tree-overlays_git.bbappend
- layers/meta-opentrons/recipes-kernel/linux/overlays/verdin-imx8mm_force-lcd-on.dts
- layers/meta-opentrons/recipes-robot/robot-app/robot-app-wayland-launch_1.0.bb
[RCORE-343](https://opentrons.atlassian.net/browse/RCORE-343)
**Overview**
Addressing some issues discovered after updating the rootfs from the opentrons desktop app
**Changes**
- Change ROBOT_MODEL to ROBOT_TYPE so we put the correct value when creating the VERSION.json file
- Added DSI-1 output to weston.ini to rotate the On-Device-Display -180 degrees so it shows up with the correct orientation 
- Added IsOnDevice=1 flag when starting opentrons-robot-app.sh script so the app knows its running on the ODD
- Added overlay to drive - DISPL_RST_CTRL_SOM - SODIMM_44 high on startup so the LCD turns on
**Todo**
> recipes-robot: A few changes around the stack to address On-Device-Display issues

- .github/actions/aws-credentials/action.yml
- .github/workflows/build-ot3-actions.yml
A series of fixes based on needed refactors and some recent build failures:
- refactor: move the aws credentialing code into an action since it was so bulky
- split caches of non-git downloads, sstate, and git downloads into separate entities
- store these entities on s3 as zips, since they contain empty directory trees that s3 will otherwise not store
> build: cache using zips to fix git cache issues

- .github/actions/build-refs/action/index.ts
- .github/actions/build-refs/dist/index.js
We weren't properly setting error messages from the build-refs action, this should help debug.
> build: fix error output in build-refs action

- layers/meta-opentrons/recipes-bsp/u-boot/files/boot.cmd.in
- layers/meta-opentrons/recipes-bsp/u-boot/u-boot-distro-boot.bbappend
- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
[RCORE-395](https://opentrons.atlassian.net/browse/RCORE-395)
We have an A/B update mechanism in place, so we should take advantage of that and enable kernel + DTB + overlay updates by hosting them in the rootfs instead of the boot partition. This way they can be updated with a rootfs update and we don't end up like the OT2 where we can't (safely) update to a newer version when the kernel + device tree are out of date.
- Load kernel + dtb + overlays from rootfs instead of boot partition
- switch between rootfs partitions 2-3 if boot fails
> recipes-bsp/u-boot: added custom u-boot script to change boot behavior

- .github/workflows/build-ot3-actions.yml
- layers/meta-opentrons/classes/get_ot_package_version.bbclass
- layers/meta-opentrons/recipes-robot/opentrons-robot-server/opentrons-robot-server_git.bb
- layers/meta-opentrons/recipes-robot/opentrons-update-server/opentrons-update-server_git.bb
This takes the version of the opentrons python classes from git.
> opentrons-robot-server: version from git

- layers/meta-opentrons/recipes-robot/nginx/files/nginx.conf
Valid protocols larger than 2M were failing because Nginx was configured to max request size of 2M so remove the max request size for the /protocols endpoint so we don't run into this in the future.
> recipes-robot/nginx: remove nginx request size limit for /protocols endpoint

- layers/meta-opentrons/recipes-core/base-files/files/custom-fstab
- layers/meta-opentrons/recipes-core/dropbear/dropbear_%.bbappend
**Closes:** [RCORE-178](https://opentrons.atlassian.net/browse/RCORE-178)
**Overview:**
We only want parts of the system to be read-write like /userfs, /var, etc for everything else we want read-only. 
**Changelog:**
- change root mount option to ro (read-only)
- create a symlink for dropbear host rsa key-file /etc/dropbear -> /var/lib/dropbear
> recipes-core/base-files/fstab: Change rootfs to read-only in fstab

- Dockerfile
Builds are failing because of an exception caused bu using python_build_util.py when attempting to run a git command as a subprocess. This was due to /volumes/opentrons not having the right permissions, so lets just label /volumes/opentrons as a safe.directory in the git config.
- set /volumes/opentrons as a safe.directory in the git config of the Dockerfile
> build: fix permission issue causing python_build_util.py to fail in Docker container.

- layers/meta-opentrons/recipes-robot/nginx/files/nginx.conf
See RSS-166 for further issue on the bug found. Essentially, this change made the `/protocols` endpoint unusable. I am still debugging a separate issue that's popping up after this conf change so I will keep this PR open until I can find the root cause.
> fix(recipes-robot): we should not set proxy headers for the /protocols endpoint in nginx conf

- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
- layers/meta-opentrons/recipes-kernel/ch341ser/ch341ser_git.bb
Adds kernel driver for [CH341SER](https://github.com/juliagoda/CH341SER) serial to USB module.
> recipes-kernel/ch341ser: add ch341ser usb driver kernel module support

- layers/meta-opentrons/recipes-robot/opentrons-mcu-firmware/opentrons-mcu-firmware.bb
- fix an issue with wrong filenames
- Dont assume the names of the binary files, instead, have ot3-firmware repo's subsystem_versions.py script deal with that so oe-core can just deal with placing the files in the correct location.
- Change structure to `{"subsystem": {"branch": branch, "version": version, "shortsha": shortsha, "files_by_revision": {"rev1": filepath}}`
> recipes-robot/opentrons-mcu-firmware: add filepath from filename provided by subsystem_versions.py 

- layers/meta-opentrons/recipes-robot/opentrons-robot-server/files/opentrons-robot-server.service
https://github.com/Opentrons/opentrons/pull/12094 allows us to set the max unused number of protocols the robot server will store via an env variable. This PR actually sets that env variable for the Flex without affecting OT-2 behavior
closes https://opentrons.atlassian.net/browse/RCORE-613
- Set max unused protocols on robot server to 20
- Low, just an env variable that has a fallback inside the robot server
[RCORE-287]: https://opentrons.atlassian.net/browse/RCORE-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> set max unused protocols on robot server to 20

- layers/meta-opentrons/recipes-robot/opentrons-mcu-firmware/opentrons-mcu-firmware.bb
https://github.com/Opentrons/ot3-firmware/pull/567 provides firmware for all electrical revisions, built and distributed to an install area and gathered by `subsystem_versions.json`. This PR takes those firmwares and makes sure they get properly gathered - using the cmake install mechanism added by previous ot3-firmware PRs - and installed, and wrapped up in opentrons-firmware.json.
This is safe to do without corresponding python-side changes because ot3-firmware establishes revision aliases for `rev1`, so we can have the files present before we get around to actually installing them.
Closes RET-1322
> opentrons-mcu-firmware: install all revisions

- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
> recipes-images/opentrons-ot3-image: add dfu-util to support rear panel board updates.

- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
We have a lot of stuff on the OT3, and the 1.5GB of space we have for system services has already been used up. However, the builds were not taking this into account and were generating images that were bigger than the partition size they were to be installed in. The system-server also does not check if the update size fits in the partition it's writing to, which caused critical files to be overwritten, and when the system restarts that would brick it. 
So first let's increase the size of the partition to 2GB, this won't get us very far but it will at least get us moving.
Secondly, we need not produce images that are larger than the partition size so let's take that into account and bail.
Ideally, we can reduce the size of our packages, but let's stop the bleeding first.
- Increase …
> recipes-images/opentrons-ot3-image: Increase rootfs size to 2GB + check max rootfs size when building.

- .github/workflows/build-ot3-actions.yml
- start.sh
We've recently been having some issues with builds stopping because diskmon says we're out of disk space. In response, we limited the size of the cache we'd download (#52 ). 
However, it kept happening occasionally: https://github.com/Opentrons/oe-core/actions/runs/4325480403/jobs/7551693531
It fails with this message:
```
WARNING: The free space of /tmp (overlay) is running low (0.049GB left)
ERROR: No new tasks can be executed since the disk space monitor action is "STOPTASKS"!
```
Though we do have a build directory called `tmp`, that's not what this is: this is about the actual `/tmp` mounted inside the build container. The thing is, `/tmp` should be a special `tmpfs` mount, a ramdisk that can page if necessary and have effectively unlimited size.
However, when we set up the image, we …
> build: use an explicit tmp volume to fix out of disk problems

- .github/workflows/build-ot3-actions.yml
This should list the refs of all three repos (oe-core, monorepo, ot3-firmware) in build output messages.
> build: list all refs in slack message

- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
- layers/meta-opentrons/recipes-robot/opentrons-user-environment/files/ot-environ.sh
- layers/meta-opentrons/recipes-robot/opentrons-user-environment/opentrons-user-environment.bb
There are a couple environment variables that need to be defined for our software to work. They're defined in systemd units for things that are run automatically, but it's helpful to also have them present in user shells for running scripts. Let's make them present there.
> layers/meta-opentrons: add OT user environment

- layers/meta-opentrons/recipes-robot/opentrons-mcu-firmware/opentrons-mcu-firmware.bb
The rear panel system recently changed to have its applications use .bin instead of .hex for the files; this makes OE complain because we told it to expect us to install only .hex. Add the rear-panel binaries to FILES.
> opentrons-mcu-firmware: allow .bin for rear panel

- layers/meta-opentrons/recipes-robot/nginx/files/nginx.conf
This PR adds configuration to NGINX to allow external access to the system server.
Also adds an explicit config to route `/system/time` to the robot server, as that endpoint is not ported to the system server yet.
Tested by uploading the edited `nginx.conf` to a robot and running `nginx -s reload`, and also uploading the system server changes from https://github.com/Opentrons/opentrons/pull/12278. 
* I was able to go to `{robot_url}:31950/system/docs` and interact with the endpoints on the system server without issue. 
* I was also about to go to `{robot_url}:31950/docs` and interact with `GET /system/time` without issue.
> recipes-robot/nginx: add system server carveout to nginx.conf

- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-robot-app.service.in
- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-robot-app.sh.in
It is now a notify service.
Don't merge before https://github.com/Opentrons/opentrons/pull/12266
> layers/meta-opentrons: app uses sd_notify

- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-robot-app-devtools.service
- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-robot-app-devtools.socket
- layers/meta-opentrons/recipes-robot/opentrons-robot-app/robot-app-wayland-launch_1.0.bb
Chrome has a [remote devtools protocol](https://chromedevtools.github.io/devtools-protocol/) that you can use to separate where you run devtools from where you're running content - pretty similar to a remote debugging interface like `gdb-server` or the mac tandem kernel debugger or whatever. That's really convenient because then we don't have to try and use the devtools on the little touchscreen.
Since electron is chrome, it's built into electron, and you can tell electron to listen on a port. The problem is, electron will only listen on that port _to localhost_, and the entire point of this exercise is to make this accessible off of localhost.
As always, systemd has a solution for this: [systemd-socket-proxyd](https://manpages.ubuntu.com/manpages/bionic/man8/systemd-socket-proxyd.8.html) …
> opentrons-robot-app: allow remote devtools

- .github/actions/build-refs/action/index.ts
- .github/actions/build-refs/dist/index.js
When we look up the latest tag, we were trying to find the literal ':latest:' in the list of tags we got back from github, which won't ever work. Instead add a tested helper function for that.
> .github: fix failure looking up tags

- layers/meta-opentrons/classes/pipenv_app_bundle.bbclass
- layers/meta-opentrons/recipes-robot/opentrons-robot-server/opentrons-robot-server.bb
- layers/meta-opentrons/recipes-robot/opentrons-system-server/opentrons-system-server.bb
- layers/meta-opentrons/recipes-robot/opentrons-update-server/opentrons-update-server.bb
The robot server wasn't being installed with the correct version, because we weren't able to set the proper environment variable to do so. Add that capability and set it in the build system for all the python servers.
> meta-opentrons: correct version for python servers

- layers/meta-opentrons/recipes-robot/opentrons-robot-server/opentrons-robot-server.bb
These will be set for internal releases. We'll have to change this before full production release.
> opentrons-robot-server: use internal release notes

- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
- layers/meta-opentrons/recipes-robot/opentrons-robot-server/opentrons-robot-server.bb
We were not storing the version of the api package that the robot server relies on. This is used by the update server to respond with the version of the loaded package, and without it we don't get a version there. On the OT-2, this is provided by the separate api package recipe, but we've folded that in to the robot server here so we need to do it in the same recipe.
Closes RQA-577
> opentrons-robot-server: store api package version

- layers/meta-opentrons/recipes-robot/opentrons-robot-server/files/opentrons-robot-server.service
This is really annoying! But we need to have a long enough timeout for now to allow for all the firmware updates.
> opentrons-robot-server: longer start timeout

- .github/workflows/build-ot3-actions.yml
- build/conf/local.conf
- layers/meta-opentrons/recipes-robot/opentrons-robot-app/opentrons-robot-app.bb
yarn and node-modules were taking up a ton of space inside the docker container causing us to run out of space, so let's move the .cache location that yarn uses to cache modules to /volumes/cache/yarn which gets bind mounted outside the containers in CI.
> build: move yarn cache location to mounted volume when building from CI

- layers/meta-opentrons/conf/machine/verdin-imx8mm.conf
- layers/meta-opentrons/recipes-kernel/linux/device-tree-overlays_git.bbappend
- layers/meta-opentrons/recipes-kernel/linux/overlays/verdin-imx8mm_M24128-eeprom_overlay.dts
We need to add the m24128 eeprom we are using in the Opentrons carrier board to the device tree so we can access the memory from userspace.
Closes: [RET-1345](https://opentrons.atlassian.net/browse/RET-1345)
Todo:
[RET-1345]: https://opentrons.atlassian.net/browse/RET-1345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> recipes-kernel: add M24128 EEPROM overlay to device tree

- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
- layers/meta-opentrons/recipes-robot/opentrons-module-firmware/opentrons-module-firmware.bb
A recipe that downloads and installs the module firmware binaries to `/usr/lib/firmware` directory to enable firmware updates for modules.
> opentrons-module-firmware: added module firmware binaries to rootfs.

- layers/meta-opentrons/recipes-robot/opentrons-robot-app/opentrons-robot-app.bb
- start.sh
The `electron_cache_dir` env variable is being ignored when set from opentrons-robot-app recipe, so lets just manually create a symlink from `~/.cache/electron` -> `/volumes/cache/electron` which bind mounts to a larger partition in the ec2 instance.
> fix(build): create symlink for electron cache dir manually

- layers/meta-opentrons/recipes-core/base-files/files/custom-fstab
Works with [this](https://github.com/Opentrons/opentrons/pull/13077) monorepo change to fix the machine-id not persisting through updates.
> recipes-core/base-files: mount the /mnt dir to /userfs/var/mnt so the machine-id can persist through updates.

- start.sh
here we go again...
We should be setting the yarn download dir to /volumes/cache/yarn within the opentrons-robot-app.bb recipe, but for some reason that's being ignored, so let's just manually set the download dir with a symlink as we do for electron.
> build(fix): Manually set yarn download dir to cached location.

- layers/meta-opentrons/recipes-robot/robot-app/robot-app.bb
Cypress is gigantic and downloads to the wrong place. Preemptively remove it from the node dependencies since it's not necessary for building the actual app.
> meta-opentrons: robot-app: remove cypress

- build/conf/local.conf
The OPENTRONS_PROJECT var is set by CI during a build, but nothing sets it for local builds so the Opentrons python packages that rely on it fail to compile.
> fix(build): add OPENTRONS_PROJECT var to local.conf so we can do local builds.

- .github/workflows/build-ot3-actions.yml
- layers/meta-opentrons/classes/pipenv_app_bundle.bbclass
- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
- layers/meta-opentrons/recipes-robot/opentrons-update-server/opentrons-update-server.bb
For whatever reason Yocto likes to remove the CRT key, which means we weren't able to actually verify the updates. So instead of installing the CRT directly on the rootfs, do an install as a postrootfs change before we create the rootfs.
> opentrons-ot3-image: fix build signing by adding signing key to the rootfs.

- .github/actions/build-refs/action/__tests__/index.test.ts
- .github/actions/build-refs/action/index.ts
- .github/actions/build-refs/dist/index.js
- layers/meta-opentrons/classes/get_ot_package_version.bbclass
- layers/meta-opentrons/recipes-robot/opentrons-robot-server/opentrons-robot-server.bb
- layers/meta-opentrons/recipes-robot/opentrons-system-server/opentrons-system-server.bb
- layers/meta-opentrons/recipes-robot/opentrons-update-server/opentrons-update-server.bb
- layers/meta-opentrons/recipes-robot/opentrons-usb-bridge/opentrons-usb-bridge.bb
Two build problems:
- We specify `OPENTRONS_PROJECT` when running pipenv, but in oe-core that's not where it's needed - it needs to be passed to the explicit get-version commands, which it now is. Here's a version json from a successful build: https://builds.opentrons.com/ot3-oe/5870014223/VERSION.json
- We need to determine that this is a release if there is _any_ tag, not just an `ot3` prefix tag
> build: fix project, fix release type

- layers/meta-opentrons/recipes-robot/opentrons-ssh-keys/opentrons-ssh-keys.bb
We weren't installing the key in the release execution branch but were still providing it in the OE recipe. At some point we should make the build mode and project actual OE build variables that you can establish recipe variants on but for now just put an empty file in there in the other branch.
> opentrons-ssh-keys: always install file

- .github/workflows/build-ot3-actions.yml
- start.sh
- Don't clear cache (downloads, sstate, git) unless the build explicitly fails and is not just canceled.
- Create symlink for pip cache so it persists through builds
> chore(build): Improve build caching so subsequent builds dont take so long.

- layers/meta-opentrons/classes/pipenv_app_bundle.bbclass
A recent pip/setuptools update made pep517 isolated builds the default. That's really good and I would like to use it but also it makes the builds incredibly slow: https://github.com/pypa/pip/issues/10060 We need to keep pep517 because it's what allows pyproject tomls to specify build deps, but by preinstalling those build deps and turning off build isolation we can make it fast again. This isn't a good general purpose solution and it will surely break at some point when we add some new package but we can cross that bridge when we come to it
> fix: make builds go fast again

- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
The rootfs being produced when creating the systemfs.ext4 filesystem was not set to a fixed size, which meant that the ext4 size varied based on what recipes were built. This has the effect of producing an image for flashing with the correct rootfs partition size of 2GB, but an ot3-system update file of varying size. Which when installed would set the new rootfs size to the varying size since the filesystem was not padded. So let's use the `IMAGE_ROOTFS_SIZE` variable to set the maximum rootfs size along with `IMAGE_OVERHEAD_FACTOR` and `IMAGE_ROOTFS_EXTRA_SPACE` so there is no additional extra space in the image other than what we've manually specified.
Also, since we delegate the creation of the rootfs (systemfs) to Yocto we don't need to have an explicit mechanism to check if the size …
> opentrons-ot3-image: set the rootfs size to a fixed value when creating the system update image.

- layers/meta-opentrons/classes/get_ot_system_version.bbclass
- layers/meta-opentrons/recipes-robot/opentrons-jupyter-notebook/files/jupyter-notebook.service
- layers/meta-opentrons/recipes-robot/opentrons-jupyter-notebook/opentrons-jupyter-notebook.bb
- layers/meta-opentrons/recipes-robot/opentrons-user-environment/opentrons-user-environment.bb
The Jupyter Notebook service did not have all the correct environment variables, so we could not get a protocol context instance. This PR adds the correct environment variables to the Jupyter Notebook systems file, since we are using the OT_SYSTEM_VERSION variable in multiple recipes we also added a helper bbclass to get this value.
Closes: [RQA-1258](https://opentrons.atlassian.net/browse/RQA-1258)
`protocol = opentrons.execute.get_protocol_api('2.15')`
[RQA-1258]: https://opentrons.atlassian.net/browse/RQA-1258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> recipes-robot/opentrons-jupyter-notebook: add env variables to fix jupyter notebook.

- layers/meta-opentrons/recipes-extended/procps/files/95-opentrons.conf
- layers/meta-opentrons/recipes-extended/procps/procps_%.bbappend
One of our robots was found unresponsive after the weekend, and could not connect over serial. We think it might be a resource allocation issue but can't verify yet, so let's enable magic SysRq keys so we can debug this when/if it happens again.
> recipes-extended/procps: Enable magic SysRq keys to debug potential kernel panics.

- layers/meta-opentrons/recipes-robot/opentrons-robot-app/opentrons-robot-app.bb
We recently removed setup-js from the shared-data makefile because it's not needed anymore, but the recipe for the ODD needed to know that. Temporarily just allow it to fail instead of removing it since sometimes it will be needed until we're forever done building old branches.
> meta-opentrons: allow s-d setup-js to fail

- layers/meta-opentrons/recipes-connectivity/networkmanager/files/opentrons-init-systemconnections.service
- layers/meta-opentrons/recipes-connectivity/networkmanager/files/wired-linklocal.nmconnection
- layers/meta-opentrons/recipes-connectivity/networkmanager/files/wired.nmconnection
- layers/meta-opentrons/recipes-connectivity/networkmanager/networkmanager_%.bbappend
We need to support falling back to link-local connections for initial installs. The way you do this with network manager is to preconfigure connections for the eth0 iface, one higher-priority one that uses dhcp and can fail and one lower-priority one that uses linklocal. These need to go into /var/lib/NetworkManager/system-connections, but of course that's not on the rootfs, so they need to get copied at boot by a custom unit.
You'll know this works if you can install this build, plug it into a computer directly, and after 30 seconds you get a link local address.
> meta-opentrons: add linklocal config for eth0

- start.sh
Some Node packages are not using the correct cached directory for downloads, leading the docker instance to balloon in size causing the builds to fail. Instead of trying to wack-mole each new package whenever a build fails, let's symlink all of the `/volumes/cache` used by the docker instance to `~/.cache` which is externally mounted to S3 and has enough space to hold our cache.
> fix(build): Create symlink to .cache so we dont run out of space

- .github/actions/build-refs/action/__tests__/index.test.ts
- .github/actions/build-refs/action/index.ts
- .github/actions/build-refs/dist/index.js
Add support for internal-release tags on ot3-firmware and oe-core. Internal release tags on those repos are formatted as internal@version. Builds that start from internal-release tags on the monorepo or here will use internal-release tags from everything instead of release tags.
> chore: allow internal-release tags

- layers/meta-opentrons/classes/pipenv_app_bundle.bbclass
Need new explicit deps for the pep517 builds since we're not using build isolation, and we should handle when local paths are relative to parent dir.
> meta-opentrons: fix some python handling

- layers/meta-opentrons/recipes-robot/opentrons-mcu-firmware/opentrons-mcu-firmware.bb
Fix the build by including the hepa-uv hex files now generated by the ot3-firmware repo.
[This](https://github.com/Opentrons/ot3-firmware/pull/743) other ot3-firmware change adds the hepa-uv entry to the `opentrons-manifest.json` file.
> recipes-robot/opentrons-mcu-firmware: add hepa-uv firmware hex files to build.

- layers/meta-opentrons/recipes-connectivity/networkmanager/files/wired.nmconnection
- layers/meta-opentrons/recipes-multimedia/gstreamer-1.0/files/gstd.service
- The loading screen service unit needs to refer to weston correctly
- the dhcp wired ethernet service needed a retry since it fails the first time
> layers/meta-opentrons: fix loading screen, connections

- layers/meta-opentrons/recipes-connectivity/mosquitto/files/1571.patch
- layers/meta-opentrons/recipes-connectivity/mosquitto/files/2894.patch
- layers/meta-opentrons/recipes-connectivity/mosquitto/files/2895.patch
- layers/meta-opentrons/recipes-connectivity/mosquitto/files/mosquitto.conf
- layers/meta-opentrons/recipes-connectivity/mosquitto/mosquitto_2.0.18.bb
- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
- layers/meta-opentrons/recipes-robot/opentrons-robot-server/opentrons-robot-server.bb
Closes RET-1417
This PR adds support for Mosquitto, a message broker that implements MQTT.
Why Mosquitto?
- It's lightweight.
- It's open source.
- It's well-documented and supported.
See [this confluence doc](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3928621089/Notifications) for more background on the notifications work. [Here's the monorepo PR](https://github.com/Opentrons/opentrons/pull/14343). 
I'm fairly confident that the config settings are what we want, but feel free to give them a lookover [here](https://mosquitto.org/man/mosquitto-conf-5.html) if you're interested. Although we use default config values, we do need to explicitly specify these values. Otherwise, mosquitto rejects any connection attempt that isn't localhost. I didn't touch any setting related to …
> layers/meta-opentrons: add mosquitto

- layers/meta-opentrons/recipes-devtools/python/python-pyzmq/club-rpath-out.patch
- layers/meta-opentrons/recipes-devtools/python/python3-pyzmq_24.0.1.bb
we need an updated pyzmq for the updated jupyter notebook
> chore:  bump the pyzmq version and update the rpath patch

- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-robot-app.service.in
This service unit has a bad dep! And while the app still starts, weirdly enough, it also breaks devtools.
> layers/meta-opentrons: fix app service unit

- layers/meta-opentrons/recipes-core/systemd/systemd_%.bbappend
In the upgrade, journald appears to have lost xz support and can't read old journals anymore. This should fix that.
Closes RET-1421
> layers/meta-opentrons: xz for journald

- layers/meta-opentrons/recipes-robot/opentrons-user-environment/files/opentrons-run-boot-scripts.service
- layers/meta-opentrons/recipes-robot/opentrons-user-environment/opentrons-user-environment.bb
This is on the OT-2 and we forgot about it up to now - provide a way for people to run stuff on the system if they want. They have to install manually, but by dropping executable scripts in
/var/user-packages/etc/boot.d/ the scripts should be run at boot.
> layers/meta-opentrons: add boot script runner

- layers/meta-opentrons/recipes-graphics/wayland/files/imx-nxp-bsp/increase-cma.conf
- layers/meta-opentrons/recipes-graphics/wayland/weston-init.bbappend
- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-robot-app.service.in
It seems like occasionally weston runs out of space to get render buffers to allocate. This crashes weston and therefore crashes the ODD and therefore displays something weird and ugly because opentrons-loading can't run either.
Let's do two things to address this:
1. The ODD can autorestart, which should prevent the problem from lingering
2. We can increase the amount of contiguous memory available to ideally prevent it from happening
More info about contiguous memory on imx/galcore: https://community.nxp.com/t5/i-MX-Processors/imx8mp-How-to-resolve-weston-crash-with-g2d-alloc-alloc-memory/m-p/1535838
Closes RQA-2353
> layers/meta-opentrons: address robot app g2d crashes

- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-loading.sh
- layers/meta-opentrons/recipes-robot/opentrons-system-server/files/opentrons-system-server.service
A few fixes and additions for OEM Mode
- add `OT_SYSTEM_SERVER_dot_env_path` dotenv file to the systemd file for the system server
- use the linux `tr` command to strip away quotes and double quotes when parsing dotenv file
- loosen the regex when parsing `oem_mode_enabled` flag
> layers/meta-opentrons: various fixes for system server oem mode

- layers/meta-opentrons/recipes-robot/opentrons-robot-server/files/95-opentrons-modules.rules
This allows us to see the absorbance reader on the file system as an `/dev/ot_module*`
> meta-opentrons/udev-rules: add rule to opentrons-modules.rules

- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-robot-app.service
While investigating an issue with the ODD, we noticed that the ODD electron app (opentrons-robot-app.service) continues to run even when the render process is killed for whatever reason. If we ever get into this state, we should quit the application so that the service exits and systemd can restart the service. This pull request ensures the service is always restarted and limits how long to wait before force-killing the process if it takes too long to restart. This PR corresponds with this monorepo pr [Opentrons/opentrons#15500](https://github.com/Opentrons/opentrons/pull/15500)
- The `opentrons-robot-app.service` (ODD app) should always restart unless explicitly stopped or disabled.
- Let's add `TimeoutStopSec=10` so the service is forced to terminate if the process is taking too long to …
> opentrons-robot-app: always restart service and force stop after 10s.

- layers/meta-opentrons/recipes-robot/opentrons-robot-server/files/opentrons-robot-server.service
Add `maximum_quick_transfer_protocols=20` to robot server service file
Closes: [PLAT-314](https://opentrons.atlassian.net/browse/PLAT-314)
[PLAT-314]: https://opentrons.atlassian.net/browse/PLAT-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> opentrons-robot-server: add maximum_quick_transfer_settings to robot server service file.

- layers/meta-opentrons/recipes-robot/opentrons-user-environment/files/opentrons_execute
- layers/meta-opentrons/recipes-robot/opentrons-user-environment/files/opentrons_simulate
- layers/meta-opentrons/recipes-robot/opentrons-user-environment/opentrons-user-environment.bb
Add explicit executable shell scripts for `opentrons_simulate` and `opentrons_execute`. 
Normally, when you install python packages that have script entrypoints, the install process will generate the scripts and put them in the appropriate place. Here, we have a separate python environment in a special directory that the system doesn't know about - it's used by setting environment variables in systemd units. That means the installation won't work. So we do it ourself here.
Closes RESC-285
> layers/meta-opentrons: binding for opentrons cli

- .github/workflows/README.md
- .github/workflows/build-branches.yml
- .github/workflows/build-ot3-actions.yml
<https://opentrons.atlassian.net/browse/RDEVOPS-133>
- document that using tags as the ref in the workflow dispatch is for release only
> Changing this to handle RP events is more than I want to do right now.  Keep building on all pushes to `oe-core` 😊
> fix(CI): document consequences of tag refs

- layers/meta-opentrons/recipes-robot/opentrons-module-firmware/opentrons-module-firmware.bb
The Flex/OT-2 robots' firmware update mechanism expects the temperature module firmware file to have the following format `temperature-module@v<version>.hex` ex. `temperature-module@v2.1.0`, however, we were saving the file as `temp-deck-arduino.ino.hex` which is incorrect. This pull request fixes this issue.
> opentrons-module-firmware: set the correct filename for the temperature module firmware.

- layers/meta-opentrons/recipes-bsp/u-boot/u-boot-distro-boot/boot.cmd.in
The CAN clock frequency has changed from 20MHz to 40MHz as of Verdin iMX8M Mini [Rev E](https://developer.toradex.com/linux-bsp/application-development/peripheral-access/can-linux/#how-to-change-can-clock-source), and since we have ordered a new batch of SOMs that will most likely be Rev E we need to support this change both at the factory to produce new robots but also for already deployed robots. This pull request updates the u-boot script to conditionally apply the "verdin-imx8mm_MCP2518_overlay.dtbo" overlay based on the SOM rev.
Closes: [PLAT-464](https://opentrons.atlassian.net/browse/PLAT-464)
- Conditionally apply the "verdin-imx8mm_MCP2518_overlay.dtbo" overlay for SOM revs lower than E.
High, while this won't affect devices on the field, it will affect new SOMs flashed, so we …
> recipes-bsp/u-boot: conditionally set can clock frequency based on SOM rev.

- layers/meta-opentrons/recipes-connectivity/networkmanager/files/dispatch-bounce-mlan0.sh
That was not how test works, and anyway we can just call it with normal pipe chaining.
This script would fire on any mlan0 down event, which could really mess up future interactions. Specifically, this would make the HTTP requests we use to connect to a wifi network fail, and then the robot would be connected after the interface got rebooted. Gross. Now it connects the first time.
Closes RQA-3087
> layers/meta-opentrons: overeager mlan0 reboot

- layers/meta-opentrons/recipes-robot/opentrons-robot-server/opentrons-robot-server.bb
For some reason `pipenv_app_bundle.bbclass` does not automatically install pyusb from both the Opentrons/api or Opentrons/robot-server Pipfile. This causes the traceback when the Plate Reader is plugged into the Flex since we are trying to import `core.usb` provided by pyusb which is missing. If the Plate Reader is plugged in when the Flex is starting up, the traceback will cause the `OT3Controller` to fail startup, leaving the robot-server in a bad state.
So let's add the `python3-pyusb` dependency at the global level so we don't crash the Flex when the Plate Reader is plugged in.
Closes: [PLAT-470](https://opentrons.atlassian.net/browse/PLAT-470)
- Add python3-pyusb dependency to the `opentrons-robot-server` recipe
low, unreleased
[PLAT-470]: …
> meta-opentrons/opentrons-robot-server: add python3-pyusb dependency to support the Plate Reader.

- layers/meta-opentrons/recipes-core/systemd/files/dns-fallback.conf
- layers/meta-opentrons/recipes-core/systemd/files/ntp-fallback.conf
- layers/meta-opentrons/recipes-core/systemd/systemd_%.bbappend
The Flex cannot reach the Google DNS + NTP servers in the USA from within China, which causes unresolved domains and out-of-sync system time, leading to issues. So let's add a few backup DNS + NTP servers that are reachable from China so we don't run into this issue.
Closes: [PLAT-473](https://opentrons.atlassian.net/browse/PLAT-473)
- Add a custom list of DNS + NTP servers including ones reachable from China.
[PLAT-473]: https://opentrons.atlassian.net/browse/PLAT-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> meta-opentrons/systemd: add DNS + NTP servers that are reachable from China.

- layers/meta-opentrons/recipes-bsp/u-boot/u-boot-distro-boot/boot.cmd.in
- internal release 
- `oe-core` tag `internal@2.1.0-alpha.0`
-  `opentrons` tag `ot3@2.1.0-alpha.0`
- first external channel tags
-  `oe-core` tag `v0.7.0`
-  `opentrons` tag `v8.1.0-alpha.0`
> Chore Release 8.1.0

- layers/meta-opentrons/recipes-connectivity/networkmanager/files/dispatch-bounce-mlan0.sh
> chore(release): merge release at robot 8.1.0 oe-core v0.7.0 into main

- layers/meta-opentrons/recipes-support/c-ares/c-ares_1.17.1.bb
The [c-ares](https://github.com/c-ares/c-ares) repo changed its source branch from master to main, this pr fixes that on our end.
> c-ares: change source branch from master to main

- layers/meta-opentrons/recipes-graphics/ttf-fonts/source-han-sans-cn-fonts/44-source-han-sans-cn.conf
- layers/meta-opentrons/recipes-graphics/ttf-fonts/source-han-sans-cn-fonts_2.004.bb
- layers/meta-opentrons/recipes-images/images/opentrons-ot3-image.bb
We are adding language localization support to the client, on the ODD we need to support the Chinese character set. This pull request adds support for that.
Closes: [PLAT-573](https://opentrons.atlassian.net/browse/PLAT-573)
[PLAT-573]: https://opentrons.atlassian.net/browse/PLAT-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> opentrons-ot3-image.bb: add chinese language support

- layers/meta-opentrons/recipes-robot/opentrons-robot-app/files/opentrons-robot-app.sh
Closes [RQA-3788](https://opentrons.atlassian.net/browse/RQA-3788)
The `opentrons-robot-app` gets stuck in a restart loop after the recent Electron upgrade due to a seg fault. The [core dump](https://github.com/user-attachments/files/18128711/opentrons-app-stack.txt) shows this is due to an interaction with wayland. Disabling the software rasterizer prevents the seg fault.
[Here is a special build](https://opentrons.slack.com/archives/C81CR4VCZ/p1734104240854619) that includes the mixpanel fix (causing an infinite spinner loop) and the new flag. The ODD now updates and boots as expected!
I've smoke tested the ODD, and there don't appear to be any unexpected animation artifacts.
Huge thanks to @sfoster1 for pairing on this one!
[RQA-3788]: …
> fix: disable software rasterizer in robot-app startup script

- layers/meta-opentrons/recipes-robot/opentrons-robot-server/files/95-opentrons-modules.rules
Let's identify the FLEX Stacker as an Opentrons module and give it a symlink!
> layers/meta-opentrons: add flex-stacker module to udev rules

- layers/meta-opentrons/recipes-robot/opentrons-systemd-units/files/opentrons-clear-fontconfig-cache.service
- layers/meta-opentrons/recipes-robot/opentrons-systemd-units/files/ot-clear-fontconfig-cache
- layers/meta-opentrons/recipes-robot/opentrons-systemd-units/opentrons-systemd-units.bb
The ODD did not recognize the simplified Chinese font when the system was updated from 8.2 or lower to 8.3.0, seems like something with Fontconfig caching the fonts from the previous installation was causing a problem. Clearing the Fontconfig cache fixes the issue, so let's add a `oneshot` systemd service that runs on startup and deletes all fontconfig cache in `/var/cache/fontconfig` and then rebuilds the fontcache with `fc-cache -rf` .
Closes: [RQA-3815](https://opentrons.atlassian.net/browse/RQA-3815)
- update from 8.2 or lower to this build and make sure that Chinese characters are displayed correctly on the ODD.
[RQA-3815]: https://opentrons.atlassian.net/browse/RQA-3815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> opentrons-systemd-units: add a systemd service to clear the fontconfig cache.

- layers/meta-opentrons/recipes-robot/opentrons-module-firmware/opentrons-module-firmware.bb
oops, I broke this in my last merge, this should fix the builds.
https://github.com/Opentrons/oe-core/pull/187
> opentrons-module-firmware: fix build by adding installing temperature module binary.

- layers/meta-opentrons/recipes-kernel/linux/linux-toradex-mainline-rt_git.bb
There is a problem accessing git.kernel.org, so let's use a clone source so we can fix the builds
```
fatal: unable to access 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/': Failed to connect to git.kernel.org port 443: Connection timed out 
```
Clone: https://kernel.googlesource.com/pub/scm/linux/kernel/git/rt/linux-stable-rt.git
> meta-opentrons/linux-kernel: use clone source for linux-stable-rt.

- layers/meta-opentrons/recipes-kernel/linux/linux-toradex-mainline-rt_git.bbappend
- layers/meta-opentrons/recipes-kernel/linux/linux-toradex-mainline_git.bbappend
The previous TWO [Opentrons/oe-core#190](https://github.com/Opentrons/oe-core/pull/190) and [Opentrons/oe-core#191](https://github.com/Opentrons/oe-core/pull/191) PRs did not fix the unreachable git.kernel.org source issue for out internal release builds.
1. Unfortunately, in PR#190, this was hidden behind the fact that our [build](https://github.com/Opentrons/oe-core/actions/runs/13553224868) passed because the download/sstatecache/git were cached in S3. After manually cleaning the cache in S3 and EC2 action runner and re-running the build, it exposed the failed recipe, which this pull request should fix.
2. Unfortunately, in PR#191, only linux-toradex-mainline was fixed even though again our test builds passed
This pull request fixes both `linux-toradex-mainline` AND …
> meta-opentrons/linux-toradex-mainline: use source clones for mainline and mainline-rt

- layers/meta-opentrons/recipes-robot/systemd/systemd-conf/opentrons-journald.conf
This [Opentrons/opentrons#18034](https://github.com/Opentrons/opentrons/issues/18034) bug filed has identified some performance issues with the Flex robot, particularly with journal logging affecting the robot-server and robot-app processes. This pull request removes the log forwarding we used to have for cloud log collection services (datadog), which we no longer do.
> recipes-robot/systemd: Dont forward journal messages to systlog daemon.

- layers/meta-opentrons/recipes-robot/systemd/systemd-conf/opentrons-journald.conf
This https://github.com/Opentrons/opentrons/issues/18034 bug identified some performance issues with the Flex robot, particularly with journal logging affecting the robot-server and robot-app processes. This pull request reduces the SyncIntervalSec from 5m to 1s to reduce the memory footprint from the logs before they are written to disk.
> recipes-robot/systemd: reduce the SyncIntervalSec from 5m to 1s to reduce memory usage.

- .github/workflows/build-ot3-actions.yml
https://github.com/Opentrons/oe-core/actions/runs/17282438606/job/49107012357#step:14:131
```shell
+ BB_NUMBER_THREADS=32
+ bitbake opentrons-ot3-image --runall=fetch
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
Following is the list of potential problems / advisories:
Fetcher failure for URL: 'https://yoctoproject.org/connectivity.html'. URL https://yoctoproject.org/connectivity.html doesn't work.
Please ensure your host's network is configured correctly.
Please ensure CONNECTIVITY_CHECK_URIS is correct and specified URIs are available.
If your ISP or network is blocking the above URL,
try with another domain name, for example by setting:
CONNECTIVITY_CHECK_URIS …
```
> fix(ci): CONNECTIVITY_CHECK_URIS added to local.conf in CI

- .github/workflows/build-ot3-actions.yml
this way it's a little easier to grab the compiled artifacts
> .github: set a job output of the s3 urls
